import GetStarted from "@/components/auth/GetStarted"

export const metadata = {
  title: "Get Started | AnchorPay",
  description: "Generated by create next app",
}

function GetStartedPage() {
  return <GetStarted/>
}

export default GetStartedPage;

